class ErrorTokenValue(Exception): ...
class ErrorRequestToService(Exception): ...
class ErrorKeyInResponse(Exception): ...
class ErrorEnvValues(Exception): ...
class ErrorLenResponse(Exception): ...
class ErrorInvalidResponse(Exception): ...
